#ifndef MESSENGER_CORE_EXPORT_H
#define MESSENGER_CORE_EXPORT_H

#include <QtCore/QtGlobal>

#if defined(MESSENGER_CORE_LIBRARY)
# define MESSENGER_CORE_EXPORT Q_DECL_EXPORT
#else
# define MESSENGER_CORE_EXPORT Q_DECL_IMPORT
#endif

#endif // MESSENGER_CORE_EXPORT_H
